import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  AuthProvider  from "@/context/AuthProvider"
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { SocketProvider } from "@/context/socket-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <SocketProvider> */}
      <AuthProvider>
      <body className={inter.className}>
      {children}
      <Toaster />
      </body>
      </AuthProvider>
      {/* </SocketProvider> */}
    </html>
  );
}
